[package]
name = "dory_ssm"
version.workspace = true
publish = false
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
dory_core = { path = "../dory_core" }
log = "0.4"

[dev-dependencies]
env_logger.workspace = true
