[package]
name = "dory_driver_s3"
version.workspace = true
edition.workspace = true
publish = false
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
dory_core.workspace = true
aws-config = { version = "1", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1"
aws-smithy-types = "1"
chrono = { workspace = true }
tokio = { workspace = true }
urlencoding = { workspace = true }

[dev-dependencies]
dory_test_support.workspace = true

[lints]
workspace = true
