[package]
name = "dory_driver_sqlite"
version.workspace = true
edition.workspace = true
publish = false
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
dory_core = { path = "../dory_core" }
hex.workspace = true
log = "0.4"
rusqlite = { workspace = true, features = ["column_decltype"] }
serde_json = { workspace = true }

[dev-dependencies]
dory_test_support.workspace = true
tempfile = "3"

[lints]
workspace = true
