use crate::query::generator::{SelectQuery, build_select_query};
use crate::query::visual_query::VisualQuerySpec;
use crate::sql::dialect::SqlDialect;

/// Wraps the SELECT generated from `spec` in a `COUNT(*)` outer query.
///
/// The inner SELECT is generated byte-for-byte identically to the data-fetch
/// query, so the count is always consistent with the row result.
///
/// All dialects supported by Dory accept `SELECT COUNT(*) FROM (<select>) AS x`
/// syntax, so no dialect-specific branching is needed here.
pub fn count_query_from_spec(spec: &VisualQuerySpec, dialect: &dyn SqlDialect) -> SelectQuery {
    let inner =
        build_select_query(spec, dialect).expect("spec must be valid when entering count path");

    SelectQuery {
        sql: format!("SELECT COUNT(*) FROM ({}) AS dory_count_subq", inner.sql),
        params: inner.params,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::query::visual_query::{
        Comparator, FilterNode, JoinKind, JoinOn, JoinStep, LiteralValue, Predicate,
        PredicateValue, Projection, SourceTable, VisualQuerySpec,
    };
    use crate::sql::dialect::{DefaultSqlDialect, PlaceholderStyle, SqlDialect};

    fn simple_spec(table: &str) -> VisualQuerySpec {
        VisualQuerySpec {
            source: SourceTable {
                schema: None,
                table: table.to_string(),
                alias: table.to_string(),
            },
            projection: Projection::All,
            joins: vec![],
            filter: None,
            group_by: vec![],
            aggregates: vec![],
            having: None,
            sort: vec![],
            limit: None,
            offset: 0,
        }
    }

    fn spec_with_join(from_table: &str, to_table: &str) -> VisualQuerySpec {
        let mut spec = simple_spec(from_table);
        spec.joins = vec![JoinStep {
            kind: JoinKind::Inner,
            from_alias: from_table.to_string(),
            to_schema: None,
            to_table: to_table.to_string(),
            to_alias: to_table.to_string(),
            on: JoinOn::FkPath {
                from_column: "id".to_string(),
                to_column: "user_id".to_string(),
            },
        }];
        spec.filter = Some(FilterNode::Predicate(Predicate {
            source_alias: to_table.to_string(),
            column: "email".to_string(),
            comparator: Comparator::Eq,
            value: PredicateValue::Single(LiteralValue::Text("alice@example.com".to_string())),
            node_id: 0,
        }));
        spec
    }

    // T20: count query wraps inner select
    #[test]
    fn count_query_wraps_inner_select() {
        let spec = spec_with_join("posts", "users");
        let result = count_query_from_spec(&spec, &DefaultSqlDialect);

        assert!(
            result.sql.starts_with("SELECT COUNT(*) FROM ("),
            "must wrap in COUNT(*) outer query, got: {}",
            result.sql
        );
        assert!(
            result.sql.ends_with(") AS dory_count_subq"),
            "must end with subquery alias, got: {}",
            result.sql
        );
        assert_eq!(result.params.len(), 1, "params must be forwarded unchanged");
    }

    #[test]
    fn count_query_params_are_forwarded() {
        let spec = spec_with_join("posts", "users");
        let inner = build_select_query(&spec, &DefaultSqlDialect).unwrap();
        let count = count_query_from_spec(&spec, &DefaultSqlDialect);

        assert_eq!(
            inner.params, count.params,
            "params must be identical between inner SELECT and COUNT wrapper"
        );
    }

    #[test]
    fn count_query_sqlite_dialect_valid_syntax() {
        struct SqliteDialect;
        impl SqlDialect for SqliteDialect {
            fn quote_identifier(&self, name: &str) -> String {
                format!("\"{}\"", name)
            }
            fn qualified_table(&self, _schema: Option<&str>, table: &str) -> String {
                format!("\"{}\"", table)
            }
            fn value_to_literal(&self, v: &crate::Value) -> String {
                DefaultSqlDialect.value_to_literal(v)
            }
            fn escape_string(&self, s: &str) -> String {
                s.replace('\'', "''")
            }
            fn placeholder_style(&self) -> PlaceholderStyle {
                PlaceholderStyle::QuestionMark
            }
        }

        let spec = simple_spec("events");
        let result = count_query_from_spec(&spec, &SqliteDialect);

        assert!(
            result.sql.contains("SELECT COUNT(*) FROM"),
            "SQLite dialect count query must contain COUNT(*), got: {}",
            result.sql
        );
        assert!(
            result.sql.contains("dory_count_subq"),
            "subquery alias must be present, got: {}",
            result.sql
        );
    }
}
