[package]
name = "dory_ipc"
edition.workspace = true
version.workspace = true
authors.workspace = true
description = "IPC protocol for Dory single-instance"
repository.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
postcard = { workspace = true }
interprocess.workspace = true
dory_core.workspace = true
dory_storage.workspace = true
uuid.workspace = true
serde_json.workspace = true
secrecy = "0.10"
async-trait = { workspace = true }
log.workspace = true
